Repository amylour/star_wars_hackathon, pull requests merged in 2023-05, with the labels that each got.

#1 Instructions: Info regarding Pull Requests and Git Management
  README.md
  documentation/branch.png
  documentation/pull request.png
  documentation/threedot.png
Labels: documentation

#16 Setup: Create basic project set-up
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: frontend

#18 Feat: Add navbar + game container
  assets/css/style.css
  index.html
Labels: frontend

#51 Chris m
  README.md
Labels: documentation

#59 Add non-desktop message + reposition start button
  assets/css/style.css
  index.html
Labels: enhancement, frontend

#60 Add Favicon files and link elements to index file
  assets/media/android-chrome-192x192.png
  assets/media/android-chrome-512x512.png
  assets/media/apple-touch-icon.png
  assets/media/favicon-16x16.png
  assets/media/favicon-32x32.png
  assets/media/favicon.ico
  assets/media/site.webmanifest
  index.html
Labels: frontend

#62 Feat: Write some basic JS outline functions
  assets/js/script.js
Labels: backend

#76 Feat: Create modal in HTML+CSS + add functionality in JS file
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: frontend, backend

#79 Saleha
  README.md
  assets/css/style.css
Labels: enhancement, frontend

#80 Feat: Create life containers on frontend + add basic JS logic
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: frontend, backend

#82 Fix/bug: Restore missing code from merge conflict
  assets/js/script.js
Labels: bug

#85 Feat: Use grogu media image design by Amy as life container
  assets/css/style.css
  assets/media/grougu_lives_2_55x40.png
Labels: enhancement, frontend

#88 Feat: Fixed spacing of timer + lives + changed title in HTML document
  assets/css/style.css
  index.html
Labels: enhancement, frontend

#96 Keiron: Points system
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: enhancement, frontend, backend

#99 Attempt fix: Change absolute file path to relative in CSS
  assets/css/style.css
Labels: bug, backend

#98 Add rules to start modal
  index.html
Labels: enhancement, frontend

#104 Keiron: Basic gameOver() function
  assets/js/script.js
Labels: backend

#108 Improvements to gameOver() + restartGame() functions
  assets/js/script.js
Labels: bug, backend

#109 Add details and gif to game over modal
  assets/css/style.css
  index.html
Labels: enhancement, frontend

#112 Feat: Create gameWon() function + modal
  assets/js/script.js
  index.html
Labels: frontend, backend

#119 Fix gameWon() function
  assets/js/script.js
  index.html
Labels: bug, backend

#120 update styling to buttons for winning and game over modal
  assets/css/style.css
  index.html
Labels: enhancement, frontend

#122 Fix: Stop life containers overflowing past 3 containers
  assets/js/script.js
Labels: bug, backend

#129 Add path to level 2 file
  assets/js/script.js
  index.html
Labels: enhancement, backend

#133 Modified start, gameWon and gameOver modals to suit Level 2 environment
  level2.html
Labels: enhancement, frontend

#135 Amy: Fix game canvas 2 for gameplay
  assets/css/style.css
  level2.html
Labels: bug, frontend

#139 Change modals and level passing to suit new mounted levels
  level2.html
  level3.html
Labels: enhancement, frontend

#140 Feat: Update modal buttons across all HTML files with bootstrap butto…
  assets/css/style.css
  index.html
  level2.html
  level3.html
Labels: enhancement, frontend

#143 Merge with "main" + modify modals to suit level(s) context + max point capacities.
  assets/js/level3.js
  index.html
  level2.html
  level3.html
Labels: enhancement, frontend

#145 Edit: Readjust spacing of points + life containers
  assets/css/style.css
Labels: enhancement, frontend

#147 Keiron: Minor final changes across app modals
  index.html
  level2.html
  level3.html
Labels: enhancement, frontend

#148 Edit: Modify Start modals with clear instructions
  index.html
  level2.html
  level3.html
Labels: enhancement, frontend

#150 Readme: Sections from introduction to design
  README.md
  documentation/saber scroll landing page (2).png
Labels: documentation

#151 Keiron: Readme commits - Credits + Deployment instructions
  README.md
Labels: documentation

#152 Readme: Bugs
  README.md
Labels: documentation

#153 Keiron: Clean up of codebase
  assets/css/style.css
  assets/js/level2.js
  assets/js/level3.js
  assets/js/script.js
  index.html
  level2.html
  level3.html
Labels: enhancement, backend

#158 Fix: Audio div/p/span tag removed for now
  assets/css/style.css
  index.html
Labels: bug

#159 Fix: Forget the remove the other divs too
  level2.html
  level3.html
Labels: bug

#160 Readme: Validators section
  README.md
  documentation/validation_results/CSS validator results.png
  documentation/validation_results/HTML validation results.png
Labels: documentation

#161 Fix: Rearrange validator testing section in README
  README.md
Labels: bug, documentation
